[phases.setup]
nixPkgs = ["nodejs_20", "postgresql"]

[phases.install]
cmds = [
  "cd /app/backend && npm install",
  "cd /app/frontend && npm install"
]

[phases.build]
cmds = [
  "cd /app/backend && npx prisma generate",
  "cd /app/backend && npm run build",
  "cd /app/frontend && npm run build"
]

[start]
cmd = "cd /app/backend && npm run start:prod"
