[phases.setup]
nixPkgs = ["nodejs_20", "postgresql"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd ../frontend && npm run build"
]

[start]
cmd = "cd backend && npm run start:prod"
